// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NqCF-OVOOR3sBZBkUDu0FLpRfUQa6Sc',
    appId: '1:642984992229:web:d65587160c385a50c5a30c',
    messagingSenderId: '642984992229',
    projectId: 'my-task-managers',
    authDomain: 'my-task-managers.firebaseapp.com',
    storageBucket: 'my-task-managers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZrh0ENP09pNgv6nOeL2cNv7qVUIMjKV0',
    appId: '1:642984992229:android:7c1f5495766db60fc5a30c',
    messagingSenderId: '642984992229',
    projectId: 'my-task-managers',
    storageBucket: 'my-task-managers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEh3MfJIPsB4TqWTBjnaDV9JhHtYC808Y',
    appId: '1:642984992229:ios:505cb36c61e7b87fc5a30c',
    messagingSenderId: '642984992229',
    projectId: 'my-task-managers',
    storageBucket: 'my-task-managers.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEh3MfJIPsB4TqWTBjnaDV9JhHtYC808Y',
    appId: '1:642984992229:ios:505cb36c61e7b87fc5a30c',
    messagingSenderId: '642984992229',
    projectId: 'my-task-managers',
    storageBucket: 'my-task-managers.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0NqCF-OVOOR3sBZBkUDu0FLpRfUQa6Sc',
    appId: '1:642984992229:web:d6193e30535df0f1c5a30c',
    messagingSenderId: '642984992229',
    projectId: 'my-task-managers',
    authDomain: 'my-task-managers.firebaseapp.com',
    storageBucket: 'my-task-managers.firebasestorage.app',
  );
}
